apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-01-fee3b021d3e3/my-repository/sample-app:v1.0
        ports:
        - containerPort: 8080
